// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Documentation',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Unify',
          collapsed: false,
          items: [
            'unify/features',
            'unify/getting-started',
          ],
        },
        {
          type: 'category',
          label: 'Gameplay Containers',
          collapsed: false,
          items: [
            'gameplay-containers/features',
            'gameplay-containers/changelog',
            'gameplay-containers/setup',
            'gameplay-containers/creating-new-items',
            'gameplay-containers/creating-new-equipment',
            'gameplay-containers/creating-new-containers',
            'gameplay-containers/creating-new-slots',
          ],
        },
        {
          type: 'category',
          label: 'Gameplay Interaction', 
          collapsed: false,
          items: [
            'gameplay-interaction/features',
            'gameplay-interaction/changelog',
            'gameplay-interaction/setup',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
